services:
  app:
    container_name: spring_app
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - db

  db:
    image: postgres
    container_name: sentry_psql
    environment:
      POSTGRES_DB: sentry
      POSTGRES_USER: user
      POSTGRES_PASSWORD: my-secret-pw
    ports:
      - "5432:5432"
